version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      # - image: huutocdai/simple_node:latest
      - image: cimg/base:2023.06
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - setup_remote_docker 
      - run:
          name : build docker file
          command: | 
            cd udagram-api-user
            docker build -t huutocdai/udagram-api-user .
            cd .. 
            cd udagram-api-feed
            docker build -t huutocdai/udagram-api-feed .
            cd .. 
            cd udagram-reverseproxy
            docker build -t huutocdai/udagram-reverseproxy .
            cd .. 
            cd udagram-frontend
            docker build -t huutocdai/udagram-frontend .
            cd ..
      - run:
          name: Login to Docker Hub
          environment:
            DOCKER_USERNAME: $DOCKER_USER
            DOCKER_PASSWORD: $DOCKER_PASS
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin     
      - run:
          name: Push image to docker hub
          command: |
            	docker image push huutocdai/udagram-api-user:latest
              docker image push huutocdai/udagram-api-feed:latest
              docker image push huutocdai/udagram-reverseproxyr:latest
              docker image push huutocdai/udagram-frontend:latest
# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build